#!/bin/bash

echo "START"

echo "Cleaning old logs"
echo " " > bob/console.log
echo " " > alice/console.log
echo " " > lily/console.log
echo " " > ross/console.log
echo " " > zach/console.log

echo "Connecting nodes:"
./eth-private-net connect bob alice
./eth-private-net connect bob lily
./eth-private-net connect bob zach
./eth-private-net connect bob ross
./eth-private-net connect alice lily
./eth-private-net connect alice zach
./eth-private-net connect alice ross
./eth-private-net connect lily zach
./eth-private-net connect lily ross
./eth-private-net connect zach ross

echo "Ensuring miner is stopped:"
./eth-private-net stopMiner bob

echo "Queuing transactions:"
counter=1
while [ $counter -le 2 ]
do
    ./eth-private-net sendTransaction alice lily
    ./eth-private-net sendTransaction lily zach
    ./eth-private-net sendTransaction alice ross
    ./eth-private-net sendTransaction alice bob
    ./eth-private-net sendTransaction ross alice
    ./eth-private-net sendTransaction zach lily
((counter++))
done


echo "Mining started:"
./eth-private-net startMiner bob
./eth-private-net forceTimeout bob 8000

wait

echo "Mining stopped:"
./eth-private-net stopMiner bob
./eth-private-net runTestScript bob printBlocks.js

echo "Parsing log:"
python3 logParser.py ./bob/console.log

echo "END"