#!/bin/bash


#echo "Cleaning bob's old log"
#rm bob/console.log
#touch bob/console.log
#chmod 777 bob/console.log

./eth-private-net connect bob alice
./eth-private-net connect bob lily
./eth-private-net connect bob zach
./eth-private-net connect bob ross
./eth-private-net connect alice lily
./eth-private-net connect alice zach
./eth-private-net connect alice ross
./eth-private-net connect lily zach
./eth-private-net connect lily ross
./eth-private-net connect zach ross
./eth-private-net startMiner bob
./eth-private-net runTestScript alice aliceToLily.js &
./eth-private-net runTestScript zach zachToRoss.js &
./eth-private-net runTestScript ross rossToLily.js &

wait

./eth-private-net runTestScript bob minerBlocksBob.js
./eth-private-net stopMiner bob
python3 logParser.py ./bob/console.log
